spring.application.name=legal-contract-management

spring.datasource.url = jdbc:mysql://localhost:3306/legal_contract_db
spring.datasource.username = root
spring.datasource.password = aayushi123

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.formate_sql=true


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=MyLegalContractManagementSystemSecretKey2026Secure
jwt.expiration=86400000